---
# https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  hugo: circleci/hugo@1.2.1

workflows:
  main:
    jobs:
      - hugo/build:
          asciidoc: true
          html-proofer: false
          version: "latest"
      - deploy:
          filters:
            branches:
              only: main
          requires:
            - hugo/build

jobs:
  deploy:
    docker:
      - image: cibuilds/base:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/rit-linux-wiki/public
    steps:
      # deploy.sh dependencies
      - run: apk add rsync

      # clone repo (required to access `.circleci/deploy.sh`)
      - run: git clone --depth=1 https://github.com/MoralCode/rit-linux-wiki.git

      # checkout generated html
      - attach_workspace:
          at: inventory

      # deploy to production
      - deploy:
          name: Deploy to GitHub Pages
          command: ./rit-linux-wiki/.circleci/deploy.sh
          steps:
            - add_ssh_keys:
                fingerprints:
                  - "68:32:07:24:d8:91:1a:4c:0b:d5:1c:f4:61:d3:07:fa"
          
